# Generated by Django 6.0.3 on 2026-03-13 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumInstalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due', 'Due'), ('grace', 'Grace'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('lapsed', 'Lapsed')], default='upcoming', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('cash', 'Cash'), ('neft', 'NEFT')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instalment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='premiums.premiuminstalment')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('single', 'Single Payment'), ('annual', 'Annual'), ('half_yearly', 'Half Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('total_instalments', models.IntegerField(default=1)),
                ('instalment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grace_period_days', models.IntegerField(default=30)),
                ('auto_debit_enabled', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_schedule', to='policy.policy')),
            ],
        ),
        migrations.AddField(
            model_name='premiuminstalment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='premiums.premiumschedule'),
        ),
        migrations.CreateModel(
            name='PremiumAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='premiums.premiumschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('discount', 'Discount'), ('loading', 'Loading'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('penalty', 'Penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='premiums.premiumschedule')),
            ],
        ),
    ]
