# Generated by Django 6.0.3 on 2026-03-13 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('death', 'Death'), ('maturity', 'Maturity'), ('surrender', 'Surrender'), ('accident', 'Accident'), ('disability', 'Disability'), ('critical_illness', 'Critical Illness'), ('hospitalization', 'Hospitalization'), ('property_damage', 'Property Damage'), ('theft', 'Theft'), ('fire', 'Fire'), ('natural_disaster', 'Natural Disaster'), ('third_party', 'Third Party Liability'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigation', 'Investigation'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('rejected', 'Rejected'), ('settled', 'Settled'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=30)),
                ('incident_date', models.DateField()),
                ('reported_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policy.policy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('nominee', 'Nominee'), ('legal_heir', 'Legal Heir'), ('other', 'Other')], max_length=30)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimants', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_on', models.DateField(default=django.utils.timezone.now)),
                ('verdict', models.CharField(choices=[('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('rejected', 'Rejected'), ('pending', 'Pending Further Info')], max_length=30)),
                ('recommended_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('investigation_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_claims', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='claims.claim')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('claim_form', 'Claim Form'), ('death_certificate', 'Death Certificate'), ('medical_report', 'Medical Report'), ('hospital_bill', 'Hospital Bill'), ('discharge_summary', 'Discharge Summary'), ('fir_copy', 'FIR Copy'), ('police_report', 'Police Report'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('bank_proof', 'Bank Proof'), ('policy_copy', 'Policy Copy'), ('photos', 'Photos / Evidence'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='claims/documents/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('internal', 'Internal Note'), ('customer', 'Customer Communication'), ('investigation', 'Investigation Note'), ('legal', 'Legal Note')], default='internal', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='claims.claim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('neft', 'NEFT'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('cash', 'Cash'), ('dd', 'Demand Draft')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payee_name', models.CharField(max_length=200)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='claims.claim')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
