# Generated by Django 6.0.3 on 2026-03-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
